# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=32)),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Search',
            },
        ),
    ]
